version: "3.4"

services:
  ng_conf_dev:
    container_name: ng_conf
    hostname: ng_conf
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile_dev
    volumes: 
      - ./app:/app
      - cert-handler_certbot-letsencrypt:/etc/letsencrypt
    ports:
      - 4200
    stdin_open: true

  ng_conf:
    container_name: ng_conf_prod
    hostname: ng_conf_prod
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4200

volumes:
  cert-handler_certbot-letsencrypt:
    external: true

networks: 
  default:
    external:
      name: the_network
