FROM node:lts-slim

RUN for i in {1..8}; do mkdir -p "/usr/share/man/man$i"; done

RUN apt-get update

RUN apt-get install git wget curl iputils-ping net-tools zsh -y

RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true

WORKDIR /app

RUN npm i -g nodemon bower @angular/cli